### ISSUE TITLE
Invalid tag name/unsupported characters shows MalformedJsonException.

### ISSUE THREAD

**Issue by sachin-handiekar** [sachin-handiekar/jInstagram#110]
When using invalid tag name or with unsupported character the request URL becomes invalid.

```
    instagram.getRecentMediaTags("test/u10191");
```

Below is the log trace - 

```
2015-09-03 12:39:58 DEBUG Instagram:1007 - Creating request for Instagram -  https://api.instagram.com/v1/tags/test/u10191/media/recent
2015-09-03 12:39:58 DEBUG Instagram:1037 - Using access_token :  ************************
2015-09-03 12:39:58 DEBUG Instagram:1050 - Sending request to Instagram...

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected EOF at line 1 column 11
    at com.google.gson.JsonParser.parse(JsonParser.java:65)
    at com.google.gson.JsonParser.parse(JsonParser.java:45)
    at org.jinstagram.utils.LogHelper.prettyPrintJSONResponse(LogHelper.java:98)
    at org.jinstagram.Instagram.createInstagramObject(Instagram.java:928)
    at org.jinstagram.Instagram.getRecentMediaTags(Instagram.java:734)
    at org.jinstagram.Instagram.getRecentMediaTags(Instagram.java:692)
    at org.jinstagram.Instagram.getRecentMediaTags(Instagram.java:680)
    at org.jinstagram.InstagramTest.testInvalidRequest(InstagramTest.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.intellij.junit4.JUnit4TestRunnerUtil$IgnoreIgnoredTestJUnit4ClassRunner.runChild(JUnit4TestRunnerUtil.java:313)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: com.google.gson.stream.MalformedJsonException: Expected EOF at line 1 column 11
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1310)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:390)
    at com.google.gson.JsonParser.parse(JsonParser.java:60)
    ... 32 more

```

Actual Response : Instagram returns a HTML page with 404 error. 
Expected Response : JSON response from Instagram with a proper error message / no result.

**Comment by alfredayibonte** [comment]
have a utility to check if internet connectivity is good before making  your api calls else find a way of solving using try catch block. 
You usually get these errors when internet connectivity is down  especially with networking libraries.

**Comment by rilaby** [comment]
@sachin-handiekar the root of the issue is known but handling is not appropriate. 
It is the responsibility of jInstagram to handle 404 response ( `com.google.gson.stream.MalformedJsonException` talks about that) and throw declared `InstagramException` every client is expecting and have a recovery section.

**Comment by rilaby** [comment]
@sachin-handiekar I've created pull request to solve the issue.
https://github.com/sachin-handiekar/jInstagram/pull/136

**Comment by mm-yuliang** [comment]
same error with "famu", good with other hashtags. not know why.
I used instagram.getRecentMediaTags("famu", 10);

using latest version 1.1.5.

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
