### ISSUE TITLE
POST is not working for relations authorized account

### ISSUE THREAD

**Issue by Ariloum** [sachin-handiekar/jInstagram#114]
Hi, yesterday I started geting error on POST message on following request. 
I was authorized my account's token with this kind of url (as you can see there is relationships at the end): 
https://api.instagram.com/oauth/authorize/?client_id=44e6baf1dc5d45a082cae725ffa2f36d&redirect_uri=http%3A%2F%2Freveal-it.appspot.com%2Foauthtest&response_type=code&scope=comments+likes+relationships
I'm using this nearby month, it was okay early and I didnt changed a bit.

Here is an error stacktrace:

**Comment by Ariloum** [comment]
org.jinstagram.exceptions.InstagramBadRequestException: APIError: This client ID is not permitted to POST relationships actions.
	at org.jinstagram.entity.common.InstagramErrorResponse.throwException(InstagramErrorResponse.java:44)
	at org.jinstagram.Instagram.handleInstagramError(Instagram.java:977)
	at org.jinstagram.Instagram.createInstagramObject(Instagram.java:941)
	at org.jinstagram.Instagram.setUserRelationship(Instagram.java:484)
	at com.nebula.insta.classes.InstagramInstance.followTo(InstagramInstance.java:507)
	at com.nebula.insta.app.App.start(App.java:203)
	at com.nebula.insta.app.App.main(App.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by Ariloum** [comment]
I've tested it with 1.1.3, 1.1.4 and 1.1.5-SNAPSHOT versions - both my accounts have same error.

**Comment by sachin-handiekar** [comment]
It looks more of a client specific error. Can you create a new client and try it out ?

**Comment by Ariloum** [comment]
I've tried it with a new account, I got this error :

**Comment by Ariloum** [comment]
But I have already created a token with relationships scope like that : 
        InstagramService service = new InstagramAuthService()
                .apiKey(clientId)
                .apiSecret(clientSecret)
                .callback(callbackUrl)
                .scope("comments likes relationships")
                .build();

**Comment by marz619** [comment]
@Ariloum @sachin-handiekar 

As far as I am aware, `POSTing` comments / likes and relationships requires special permissions on the client given by Instagram as stated in their docs [here](https://instagram.com/developer/endpoints/comments/#post_media_comments) and this is the [form](https://help.instagram.com/contact/185819881608116) to request POST permissions.

Regards

**Comment by sachin-handiekar** [comment]
Closing the ticket... Re-open if needed
